### ISSUE TITLE
config.sh: cannot import name 'ComposeResult' from 'textual.app'

### ISSUE THREAD

**Issue by roliver-rpi** [raspberrypi/rpi-sb-provisioner#23]
Debian's python3-textual packages version 0.1.13

ComposeResult was introduced in https://github.com/Textualize/textual/commit/4090d351684342b8e28ef9d5451c7c821e18d1ae (later released in v0.2.0 (The CSS Release) in October 2022).

The latest Textual release is v0.76.0. Debian Trixie/Sid package v0.52.1

**Comment by tdewey-rpi** [comment]
ACK, agreed this is a problem.

We explored the possibility of using a later Debian-packaged Textual - but that is a no-go for example-derived code.

As such, I think we need to explore putting this stuff into a venv, and _that_ might mean we need to drop nfpm in place of debuild to gain access to dh_virtualenv.
